name: Create and publish a Docker image

on:
  push:
    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  # Run tests for any PRs.
  # pull_request:

env:
  # REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}
  REGISTRY: docker.io
  IMAGE_NAME: nxest/xlabs-developer-platform

jobs:
  push:
    runs-on: ubuntu-latest
     # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    # permissions:
    #   contents: read
    #   packages: write
    #   attestations: write
    #   id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
      
      - name: Install package
        run: |
          yarn install --immutable

      - name: Node build
        run: |
          yarn tsc
          yarn build:backend

      - name: Login to dockerhub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          # username: ${{ github.actor }}
          # password: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Setup qemu
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all

      - name: Setup buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Push image
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^native-v//')

          yarn build-image \
            --tag $IMAGE_NAME:$VERSION \
            --tag $IMAGE_NAME:lastest \
            --platform linux/amd64,linux/arm64 \
            --push